---
- name: Retrieve available authselect profiles
  ansible.builtin.command: ls /usr/share/authselect/default/
  register: authselect_cmd
  changed_when: false
  when: authselect_enabled
  tags:
    - pam
    - validate

- name: Set available authselect profile facts
  ansible.builtin.set_fact:
    authselect_default_profiles: "{{ authselect_cmd.stdout_lines | default([]) }}"
  changed_when: false
  when: authselect_enabled
  tags:
    - pam
    - validate

- name: Validate authselect booleans
  ansible.builtin.assert:
    that:
      - authselect_enabled is boolean
      - authselect_create_profile is boolean
    quiet: true
  tags:
    - pam
    - validate

- name: Validate pam-auth-update controls
  ansible.builtin.assert:
    that:
      - pam_auth_update_enabled is boolean
      - pam_auth_update_profiles is iterable
      - auth_deny_after | int >= 1
      - auth_deny_after | int <= 5
      - auth_unlock_time | int == 0 or auth_unlock_time | int >= 900
      - auth_unlock_time | int <= 604800
      - auth_remember | int >= 24
      - auth_min_length | int >= 14
      - auth_difok is none or auth_difok | int >= 2
      - auth_maxrepeat is none or (auth_maxrepeat | int >= 1 and auth_maxrepeat | int <= 3)
      - auth_maxsequence is none or (auth_maxsequence | int >= 1 and auth_maxsequence | int <= 3)
      - auth_root_unlock_time is none or auth_root_unlock_time | int >= 60
    quiet: true
  tags:
    - pam
    - validate

- name: Validate authselect custom profile settings
  ansible.builtin.assert:
    that:
      - authselect_custom_profile_name is string
      - authselect_custom_profile_name | length > 0
      - authselect_base_profile in authselect_default_profiles
        or authselect_base_profile in ['cis_local', 'cis_winbind', 'cis_sssd']
    quiet: true
  when:
    - authselect_enabled
    - authselect_create_profile
  tags:
    - pam
    - validate

- name: Validate authselect selected profile
  ansible.builtin.assert:
    that:
      - authselect_select_profile in authselect_default_profiles
        or authselect_select_profile in ['cis_local', 'cis_winbind', 'cis_sssd']
    quiet: true
  when:
    - authselect_enabled
    - not authselect_create_profile
  tags:
    - pam
    - validate

- name: Validate authselect options
  ansible.builtin.assert:
    that:
      - item in lookup('vars', '_authselect_' + authselect_base_profile + '_options')
    quiet: true
  loop: "{{ authselect_options | default([]) }}"
  when: authselect_enabled
  tags:
    - pam
    - validate

- name: Validate mandatory numeric variables
  ansible.builtin.assert:
    that:
      - lookup('vars', item) | int(-100) > -100
    quiet: true
  loop:
    - auth_remember
    - auth_deny_after
    - auth_fail_interval
    - auth_unlock_time
    - auth_retry
    - auth_min_length
    - auth_dcredit
    - auth_ucredit
    - auth_ocredit
    - auth_lcredit
  loop_control:
    label: "{{ item }}={{ lookup('vars', item) }}"
  tags:
    - pam
    - validate

- name: Validate optional numeric variables
  ansible.builtin.assert:
    that:
      - lookup('vars', item) | int(-100) > -100
    quiet: true
  when: lookup('vars', item) is not none
  loop:
    - auth_minclass
    - auth_maxrepeat
    - auth_maxsequence
    - auth_maxclassrepeat
    - auth_gecoscheck
    - auth_dictcheck
    - auth_usercheck
    - auth_usersubstr
    - auth_enforcing
    - auth_difok
    - auth_root_unlock_time
  loop_control:
    label: "{{ item }}={{ lookup('vars', item) }}"
  tags:
    - pam
    - validate

- name: Validate optional string variables
  ansible.builtin.assert:
    that:
      - lookup('vars', item) is string
      - lookup('vars', item) | length > 0
    quiet: true
  when: lookup('vars', item) is not none
  loop:
    - auth_faillock_dir
    - auth_admin_group
    - auth_remember_file
    - auth_dictpath
  loop_control:
    label: "{{ item }}={{ lookup('vars', item) }}"
  tags:
    - pam
    - validate

- name: Validate boolean variables
  ansible.builtin.assert:
    that:
      - lookup('vars', item) is boolean
    quiet: true
  loop:
    - auth_enforce_for_root
    - auth_local_users_only
    - auth_audit
    - auth_silent
    - auth_no_log_info
    - auth_even_deny_root
    - auth_pwhistory_enforce_for_root
    - auth_pwhistory_use_authtok
  loop_control:
    label: "{{ item }}={{ lookup('vars', item) }}"
  tags:
    - pam
    - validate
