---

- name: Retrieve available profiles
  ansible.builtin.shell: "ls /usr/share/authselect/default/"
  register: authselect_cmd
  changed_when: false

- name: Set variable with results
  ansible.builtin.set_fact:
    authselect_default_profiles: "{{ authselect_cmd.stdout_lines }}"

- name: Validate authselect_enabled value
  ansible.builtin.assert:
    that:
      - authselect_enabled is defined
      - authselect_enabled | type_debug == 'bool'
    quiet: yes

- name: Validate authselect_create_profile value
  ansible.builtin.assert:
    that:
      - authselect_create_profile is defined
      - authselect_create_profile | type_debug == 'bool'
    quiet: yes

- name: Validate authselect_custom_profile_name value
  ansible.builtin.assert:
    that:
      - authselect_custom_profile_name is defined
      - authselect_custom_profile_name is string
      - authselect_custom_profile_name | length > 0
    quiet: yes
  when: authselect_enabled and authselect_create_profile

- name: Validate authselect_base_profile value
  ansible.builtin.assert:
    that:
      - authselect_base_profile is defined
      - authselect_base_profile in authselect_default_profiles or authselect_base_profile in ['cis_local', 'cis_winbind', 'cis_sssd']
    quiet: yes
  when: authselect_enabled and authselect_create_profile

- name: Validate authselect_select_profile value
  ansible.builtin.assert:
    that:
      - authselect_select_profile is defined
      - authselect_select_profile in authselect_default_profiles or authselect_select_profile in ['cis_local', 'cis_winbind', 'cis_sssd']
    quiet: yes
  when: authselect_enabled and not authselect_create_profile

- name: Validate authselect options
  ansible.builtin.assert:
    that:
      - item is defined
      - item in vars['_authselect_' + authselect_base_profile + '_options']
    quiet: yes
  loop: "{{ authselect_options | default([]) }}"

- name: Validate numeric variables are correctly set
  ansible.builtin.assert:
    that:
      - vars[item] is defined
      - vars[item] | int(-100) > -100
    quiet: yes
  loop:
    - auth_remember
    - auth_deny_after
    - auth_unlock_time
    - auth_retry
    - auth_min_length
    - auth_dcredit
    - auth_ucredit
    - auth_ocredit
    - auth_lcredit
  loop_control:
    label: "{{ item }}: {{ vars[item] | default('undefined') }}"

- name: Validate optional numeric variables are correctly set
  ansible.builtin.assert:
    that:
      - vars[item] | int(-100) > -100
    quiet: yes
  when: vars[item] is defined
  loop:
    - auth_maxrepeat
    - auth_maxclassrepeat
    - auth_gecoscheck
    - auth_dictcheck
    - auth_usercheck
    - auth_usersubstr
    - auth_enforcing
    - auth_difok
    - auth_root_unlock_time
  loop_control:
    label: "{{ item }}: {{ vars[item] | default('undefined') }}"

- name: Validate booleans
  ansible.builtin.assert:
    that:
      - vars[item] is defined
      - vars[item] | type_debug == 'bool'
    quiet: yes
  when: vars[item] is defined
  loop:
    - auth_enforce_for_root
    - auth_local_users_only
    - auth_audit
    - auth_silent
    - auth_no_log_info
  loop_control:
    label: "{{ item }}: {{ vars[item] | default('undefined') }}"
