---
- name: Ensure authselect is installed
  ansible.builtin.package:
    name: authselect
    state: present
  tags:
    - pam
    - install

- name: Create authselect vendor profile directories
  ansible.builtin.file:
    path: "/usr/share/authselect/vendor/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - cis_local
    - cis_sssd
    - cis_winbind
  tags:
    - pam
    - config

- name: Copy authselect vendor profile files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
    force: false
  loop:
    - {src: winbind/README.j2, dest: /usr/share/authselect/vendor/cis_winbind/README}
    - {src: winbind/REQUIREMENTS.j2, dest: /usr/share/authselect/vendor/cis_winbind/REQUIREMENTS}
    - {src: winbind/dconf-db.j2, dest: /usr/share/authselect/vendor/cis_winbind/dconf-db}
    - {src: winbind/dconf-locks.j2, dest: /usr/share/authselect/vendor/cis_winbind/dconf-locks}
    - {src: winbind/fingerprint-auth.j2, dest: /usr/share/authselect/vendor/cis_winbind/fingerprint-auth}
    - {src: winbind/nsswitch.conf.j2, dest: /usr/share/authselect/vendor/cis_winbind/nsswitch.conf}
    - {src: winbind/password-auth.j2, dest: /usr/share/authselect/vendor/cis_winbind/password-auth}
    - {src: winbind/postlogin.j2, dest: /usr/share/authselect/vendor/cis_winbind/postlogin}
    - {src: winbind/smartcard-auth.j2, dest: /usr/share/authselect/vendor/cis_winbind/smartcard-auth}
    - {src: winbind/system-auth.j2, dest: /usr/share/authselect/vendor/cis_winbind/system-auth}
    - {src: winbind/switchable-auth.j2, dest: /usr/share/authselect/vendor/cis_winbind/switchable-auth}
    - {src: local/README.j2, dest: /usr/share/authselect/vendor/cis_local/README}
    - {src: local/REQUIREMENTS.j2, dest: /usr/share/authselect/vendor/cis_local/REQUIREMENTS}
    - {src: local/dconf-db.j2, dest: /usr/share/authselect/vendor/cis_local/dconf-db}
    - {src: local/dconf-locks.j2, dest: /usr/share/authselect/vendor/cis_local/dconf-locks}
    - {src: local/fingerprint-auth.j2, dest: /usr/share/authselect/vendor/cis_local/fingerprint-auth}
    - {src: local/nsswitch.conf.j2, dest: /usr/share/authselect/vendor/cis_local/nsswitch.conf}
    - {src: local/password-auth.j2, dest: /usr/share/authselect/vendor/cis_local/password-auth}
    - {src: local/postlogin.j2, dest: /usr/share/authselect/vendor/cis_local/postlogin}
    - {src: local/smartcard-auth.j2, dest: /usr/share/authselect/vendor/cis_local/smartcard-auth}
    - {src: local/system-auth.j2, dest: /usr/share/authselect/vendor/cis_local/system-auth}
    - {src: local/switchable-auth.j2, dest: /usr/share/authselect/vendor/cis_local/switchable-auth}
    - {src: sssd/README.j2, dest: /usr/share/authselect/vendor/cis_sssd/README}
    - {src: sssd/REQUIREMENTS.j2, dest: /usr/share/authselect/vendor/cis_sssd/REQUIREMENTS}
    - {src: sssd/dconf-db.j2, dest: /usr/share/authselect/vendor/cis_sssd/dconf-db}
    - {src: sssd/dconf-locks.j2, dest: /usr/share/authselect/vendor/cis_sssd/dconf-locks}
    - {src: sssd/fingerprint-auth.j2, dest: /usr/share/authselect/vendor/cis_sssd/fingerprint-auth}
    - {src: sssd/nsswitch.conf.j2, dest: /usr/share/authselect/vendor/cis_sssd/nsswitch.conf}
    - {src: sssd/password-auth.j2, dest: /usr/share/authselect/vendor/cis_sssd/password-auth}
    - {src: sssd/postlogin.j2, dest: /usr/share/authselect/vendor/cis_sssd/postlogin}
    - {src: sssd/smartcard-auth.j2, dest: /usr/share/authselect/vendor/cis_sssd/smartcard-auth}
    - {src: sssd/system-auth.j2, dest: /usr/share/authselect/vendor/cis_sssd/system-auth}
    - {src: sssd/switchable-auth.j2, dest: /usr/share/authselect/vendor/cis_sssd/switchable-auth}
  tags:
    - pam
    - config

- name: Create a custom authselect profile
  ansible.builtin.command:
    cmd: >-
      /usr/bin/authselect create-profile {{ authselect_custom_profile_name }} -b {{ authselect_base_profile }}
  register: authselect_create_result
  when: authselect_create_profile
  failed_when: authselect_create_result.rc not in [0, 4]
  changed_when: authselect_create_result.rc == 0
  tags:
    - pam
    - config

- name: Check current authselect profile
  ansible.builtin.command: authselect current
  register: authselect_current_cmd
  failed_when: authselect_current_cmd.rc not in [0, 2]
  changed_when: false
  tags:
    - pam
    - validate

- name: Store current authselect profile name
  ansible.builtin.set_fact:
    authselect_current_profile: >-
      {{
        authselect_current_cmd.stdout_lines
        | select('match', '^Profile ID:')
        | map('regex_replace', '^Profile ID:\s*', '')
        | first
        | default('no-profile-set')
      }}
  changed_when: false
  tags:
    - pam
    - validate

- name: Select authselect profile
  vars:
    authselect_profile_name: >-
      {{ 'custom/' ~ authselect_custom_profile_name if authselect_create_profile else authselect_select_profile }}
  ansible.builtin.command:
    cmd: >-
      authselect select -b --force {{ authselect_profile_name }} {{ authselect_options | join(' ') }}
  register: authselect_select_result
  changed_when: authselect_select_result.rc == 0
  when: authselect_current_profile != authselect_profile_name
  notify: Authselect apply changes
  tags:
    - pam
    - config
