---

- name: Ensure libpam-pwquality is installed
  ansible.builtin.apt:
    name: libpam-pwquality
    state: present
    update_cache: yes
    cache_valid_time: 3600

# Not using pamd module because the file already has a line
# that just need to be uncommented
- name: Ensure access to the su command is restricted
  tags:
    - su_restrict
  block:
    - name: "Ensure group exists: {{ auth_su_group }}"
      ansible.builtin.group:
        name: "{{ auth_su_group }}"
        state: present

    - name: "Add root to group: {{ auth_su_group }}"
      ansible.builtin.user:
        name: root
        groups: "{{ auth_su_group }}"
        append: yes

- name: Copy Debian/Ubuntu templates
  ansible.builtin.template:
    src: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/{{ item }}.j2"
    dest: "/etc/pam.d/{{ item }}"
    force: yes
    owner: root
    group: root
    mode: '0644'
  loop:
    - common-account
    - common-auth
    - common-password
    - common-session
    - common-session-noninteractive
    - su
