---
# tasks file for pam

- name: Check input variables
  ansible.builtin.include_tasks: asserts.yml
  tags:
    - pam
    - validate

- name: Configure authselect
  ansible.builtin.include_tasks: authselect.yml
  when: authselect_enabled
  tags:
    - pam
    - config

- name: Configure Debian and Ubuntu PAM with pam-auth-update
  ansible.builtin.include_tasks: Debian_pam.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - pam
    - config

- name: Configure Red Hat family PAM settings
  ansible.builtin.include_tasks: RedHat_pam.yml
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - pam
    - config

- name: Configure pwquality.conf on non-Debian platforms
  ansible.builtin.include_tasks: pwquality.yml
  when: ansible_facts['os_family'] != 'Debian'
  tags:
    - pam
    - config

- name: Configure pwhistory.conf on non-Debian platforms
  ansible.builtin.include_tasks: pwhistory.yml
  when: ansible_facts['os_family'] != 'Debian'
  tags:
    - pam
    - config

- name: Configure faillock.conf on non-Debian platforms
  ansible.builtin.include_tasks: faillock.yml
  when: >-
    ansible_facts['os_family'] != 'Debian' and
    (
      ansible_facts['distribution'] == 'Fedora' or
      authselect_enabled
    )
  tags:
    - pam
    - config
