---
- name: Update /etc/security/pwhistory.conf
  ansible.builtin.template:
    src: pwhistory.conf.j2
    dest: /etc/security/pwhistory.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags:
    - pam
    - config
