---
# Run tasks to configure pwquality.conf file

# Configure pwquality.conf settings
# These settigs are used later on pam modules
- name: Update /etc/security/pwquality.conf
  ansible.builtin.template:
    src: pwquality.conf.j2
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
