---
- name: Copy non-authselect PAM templates
  ansible.builtin.template:
    src: "redhat_noauth/{{ item }}.j2"
    dest: "/etc/pam.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - system-auth
    - password-auth
  when: not authselect_enabled
  tags:
    - pam
    - config

- name: Check if su is installed
  ansible.builtin.stat:
    path: /bin/su
  register: pam_su_binary
  tags:
    - pam
    - validate

- name: Ensure su restriction group exists
  ansible.builtin.group:
    name: "{{ auth_su_group }}"
    state: present
  when: pam_su_binary.stat.exists
  tags:
    - pam
    - config

- name: Ensure pam.d/su file has pam_wheel enabled
  ansible.builtin.lineinfile:
    path: /etc/pam.d/su
    regexp: '^\s*#?\s*auth(\s+)required(\s+)pam_wheel.so\s*(use_uid)?\s*(group=.+?)?\s*$'
    line: 'auth required pam_wheel.so use_uid group={{ auth_su_group }}'
    state: present
  when: pam_su_binary.stat.exists
  tags:
    - pam
    - config

- name: Ensure root is a member of su restriction group
  ansible.builtin.user:
    name: root
    groups: "{{ auth_su_group }}"
    append: true
  when: pam_su_binary.stat.exists
  tags:
    - pam
    - config
