---
name: CI

'on':
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "0 5 * * 0"

defaults:
  run:
    working-directory: 'guidugli.pam'   

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: 'guidugli.pam'
      - name: molecule
        uses: robertdebock/molecule-action@5.0.0
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - centos8
          - centos7
          - ubuntu2204
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10
          - fedora34
          - fedora35
          - fedora36
          
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: 'guidugli.pam'
      - name: molecule
        uses: robertdebock/molecule-action@5.0.0
        with:
          MOLECULE_DISTRO: "${{ matrix.image }}"
          options: parallel
          scenario: default
